### ISSUE TITLE
抱歉问下

### ISSUE THREAD

**Issue by qinjiajuny** [linsir6/travelNotes#2]
我在运行该项目时遇到了无法登陆的问题，尝试了注册也显示注册失败。寻找项目的数据库也无果。所以我想问下大佬你能方便告知下数据库或者给我个账户密码来登陆学习该项目吗？

**Comment by linsir6** [comment]
https://github.com/linsir6/graduateDesign   看一下这个仓库吧，这里面 即有后台程序，也有android代码
